#!/usr/bin/env python3
"""Bake symbols.json into a C header (name -> vaddr table + build-id guard)."""
import json
import sys

def main():
    if len(sys.argv) != 3:
        raise SystemExit("usage: gen_symbols_header.py symbols.json symbols_gen.h")
    d = json.load(open(sys.argv[1]))
    hooks = d["hooks"]
    skips = d.get("skips", {})
    with open(sys.argv[2], "w") as f:
        w = f.write
        w("/* generated by gen_symbols_header.py — do not edit */\n")
        w("#ifndef AGY_SYMBOLS_GEN_H\n#define AGY_SYMBOLS_GEN_H\n#include <stdint.h>\n\n")
        w('#define AGY_BUILD_ID "%s"\n' % d.get("build_id", ""))
        w("#define AGY_TEXT_BASE 0x%xULL\n\n" % d.get("text_base", 0))
        # vaddr = function entry; skip = bytes past the stack-check prologue (hook
        # there so Go's morestack re-enters the real entry, not our trampoline).
        w("static const struct { const char *name; uint64_t vaddr; uint32_t skip; } AGY_SYMS[] = {\n")
        for name, addr in hooks.items():
            w('    { "%s", 0x%xULL, %d },\n'
              % (name.replace('\\', '\\\\').replace('"', '\\"'), addr, skips.get(name, 0)))
        w("};\n")
        w("static const int AGY_NSYMS = %d;\n\n" % len(hooks))
        w("static uint64_t agy_sym(const char *name) {\n")
        w("    for (int i = 0; i < AGY_NSYMS; i++)\n")
        w("        if (__builtin_strcmp(AGY_SYMS[i].name, name) == 0) return AGY_SYMS[i].vaddr;\n")
        w("    return 0;\n}\n\n")
        w("static uint32_t agy_skip(const char *name) {\n")
        w("    for (int i = 0; i < AGY_NSYMS; i++)\n")
        w("        if (__builtin_strcmp(AGY_SYMS[i].name, name) == 0) return AGY_SYMS[i].skip;\n")
        w("    return 0;\n}\n\n")
        w("#endif\n")
    print("wrote %s (%d symbols, build-id %s)" % (sys.argv[2], len(hooks), d.get("build_id", "")))

if __name__ == "__main__":
    main()
